version: "3.9"
services:
  backend:
    build: ./backend
    env_file: .env
    ports:
      - "5000:5000"
    depends_on:
      - db
      - redis

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: modular_portal
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"

  celery:
    build: ./backend
    command: celery -A app.celery worker --loglevel=info
    depends_on:
      - backend
      - redis
